config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from . import views

urlpatterns = [
    path("", views.HomeView, name="home"),
    # Uncomment for maintenance
    #path("", views.MaintenanceView, name="maintenance"),
    path("search/", views.autocompleteModel, name="search"),
    path("advanced_search", views.advanced_search, name="advanced_search"),
    path("advanced_search_api", views.advanced_search_form, name="advanced_search_api"),
    path("index/", views.index, name="index"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path(
        "tutorial/", TemplateView.as_view(template_name="pages/tutorial.html"), name="tutorial"
    ),
    path(
        "statistics/", TemplateView.as_view(template_name="pages/statistics.html"), name="statistics"
    ),
    path("download/signature/<str:sigid>", views.download_signature, name="download_sig"),
    path("download/job/<int:jobid>", views.download_job_result, name="download_job"),
    path(
        "help/", TemplateView.as_view(template_name="pages/help.html"), name="help"
    ),
    path(
        "graphs/", views.graph_data, name="graph"
    ),
    path("unauthorized", views.render_403, name="unauthorized"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("groups/", include("toxsign.groups.urls", namespace="groups")),
    path("users/", include("toxsign.users.urls", namespace="users")),
    path("superprojects/", include("toxsign.superprojects.urls", namespace="superprojects")),
    path("projects/", include("toxsign.projects.urls", namespace="projects")),
    path("assays/", include("toxsign.assays.urls", namespace="assays")),
    path("signatures/", include("toxsign.signatures.urls", namespace="signatures")),
    path("tools/", include("toxsign.tools.urls", namespace="tools")),
    path("jobs/", include("toxsign.jobs.urls", namespace="jobs")),
    path("genes", include("toxsign.genes.urls", namespace="genes")),
    path("clusters/", include("toxsign.clusters.urls", namespace="clusters")),
    path("accounts/", include("allauth.urls")),
    path("ontologies/", include("toxsign.ontologies.urls", namespace="ontologies")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

toxsign/genes/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'genes'
# Define urls here
urlpatterns = [
    re_path(r'^gene-autocomplete/$', GeneAutocomplete.as_view(), name='gene-autocomplete'),
    path('gene/<int:gene_id>', get_gene, name="get_gene")
]

toxsign/jobs/urls.py
from django.urls import path
from toxsign.jobs import views


app_name = 'jobs'
# Define urls here
urlpatterns = [
    # ex: /jobs/
    path('running_jobs/', views.running_jobs_view, name='running_jobs'),
    path('partial_running_jobs/', views.partial_running_jobs_view, name='partial_running_jobs'),
    path('delete_job/<int:pk>', views.Delete_job, name='delete_job'),
    # ex: /jobs/5/
    # the 'name' value as called by the {% url %} template tag
    path('<int:pk>/result', views.DetailView, name='results'),
    path('<int:pk>/result/<str:file_name>', views.DownloadView, name='results_download'),
]

toxsign/superprojects/urls.py
from django.urls import path
from toxsign.superprojects import views

app_name = "superprojects"
urlpatterns = [
    path('create/', views. create_superproject, name='superproject_create'),
    path('edit/<str:spjid>/', views.edit_superproject, name='superproject_edit'),
    path('unlink/<str:spjid>/<str:prjid>', views.unlink_project, name='superproject_unlink'),
    path('<str:spjid>/', views.DetailView, name='detail')
]

toxsign/tools/urls.py
from django.urls import path
from toxsign.tools import views

app_name = 'tools'
# Define urls here
urlpatterns = [
    # ex: /tools/
    path('', views.IndexView.as_view(), name='index'),
    path('dist/results/<int:job_id>', views.distance_analysis_results, name='run_dist_results'),
    path('dist/results/<int:job_id>/table', views.distance_analysis_table, name='run_dist_table'),
    path('enrich/results/<int:job_id>', views.functional_analysis_results, name='run_enrich_results'),
    path('predict/results/<int:job_id>', views.prediction_tool_results, name='run_predict_results'),
    path('cluster_dist/results/<int:job_id>', views.cluster_dist_results, name='run_cluster_dist_results'),
    path('enrich/results/<int:job_id>/table', views.functional_analysis_full_table, name='run_enrich_table_full'),
    path('enrich/results/<int:job_id>/table/<str:type>', views.functional_analysis_partial_table, name='run_enrich_table_partial'),
    path('dist/', views.distance_analysis_tool, name='run_dist'),
    path('enrich/', views.functional_analysis_tool, name='run_enrich'),
    path('cluster_dist/', views.cluster_dist_tool, name='run_cluster_dist'),
    path('predict/', views.prediction_tool, name='run_predict'),
]

toxsign/users/urls.py
from django.urls import path

from toxsign.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
    dismiss_notification,
    accept_group_invitation
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
    path("notification/dismiss/<int:notification_id>", view=dismiss_notification, name="dismiss_notification"),
    path("notification/accept/<int:notification_id>", view=accept_group_invitation, name="accept_group_invitation"),
]

toxsign/assays/forms.py
from django import forms

from django.forms.models import inlineformset_factory

from dal import autocomplete
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout
from crispy_forms.bootstrap import FormActions
from toxsign.assays.models import Assay, Factor, ChemicalsubFactor
from toxsign.ontologies.models import Cell, CellLine, Chemical, Species, Tissue

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


class AssayCreateForm(forms.ModelForm):

    cell_line = forms.ModelChoiceField(
                    queryset=CellLine.objects.all(),
                    required=False,
                    widget=autocomplete.ModelSelect2(url='/ontologies/cellline-autocomplete')
                    )
    cell = forms.ModelChoiceField(
                queryset=Cell.objects.all(),
                required=False,
                widget=autocomplete.ModelSelect2(url='/ontologies/cell-autocomplete')
                )
    organism = forms.ModelChoiceField(
                    queryset=Species.objects.all(),
                    required=False,
                    widget=autocomplete.ModelSelect2(url='/ontologies/species-autocomplete')
                    )
    tissue = forms.ModelChoiceField(
                queryset=Tissue.objects.all(),
                required=False,
                widget=autocomplete.ModelSelect2(url='/ontologies/tissue-autocomplete')
                )

    class Meta:
        model = Assay
        exclude = ("tsx_id", "created_at", "created_by", "updated_at", "project")

    def __init__(self, *args, **kwargs):
        self.assay = kwargs.pop('assay', None)

        super(AssayCreateForm, self).__init__(*args, **kwargs)

        if self.assay:
            self.fields['name'].initial = self.assay.name
            self.fields['additional_info'].initial = self.assay.additional_info
            self.fields['experimental_design'].initial = self.assay.experimental_design
            self.fields['dev_stage'].initial = self.assay.dev_stage
            self.fields['generation'].initial = self.assay.generation
            self.fields['sex_type'].initial = self.assay.sex_type
            self.fields['exp_type'].initial = self.assay.exp_type
            self.fields['project'].initial = self.assay.project
            self.fields['organism'].initial = self.assay.organism
            self.fields['tissue'].initial = self.assay.tissue
            self.fields['cell'].initial = self.assay.cell
            self.fields['cell_line'].initial = self.assay.cell_line

        self.helper = FormHelper(self)
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('save', 'Save'))


class AssayEditForm(AssayCreateForm):

    def __init__(self, *args, **kwargs):
        super(AssayCreateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('save', 'Save'))


class FactorCreateForm(forms.ModelForm):

    class Meta:
        model = Factor
        exclude = ("tsx_id", "created_at", "created_by", "updated_at", )

    def __init__(self, *args, **kwargs):
        self.assays = kwargs.pop('assay')
        self.factor = kwargs.pop('factor', None)

        super(FactorCreateForm, self).__init__(*args, **kwargs)

        self.fields['assay'].queryset = self.assays
        if self.assays.count() == 1:
            self.fields['assay'].initial = self.assays.first()

        if self.factor:
            self.fields['name'].initial = self.factor.name
            self.fields['assay'].initial = self.factor.assay

        self.helper = FormHelper(self)
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('save', 'Save'))

class FactorEditForm(FactorCreateForm):

    def __init__(self, *args, **kwargs):
        self.assays = kwargs.pop('assay')
        super(FactorCreateForm, self).__init__(*args, **kwargs)
        self.fields['assay'].queryset = self.assays
        self.helper = FormHelper(self)
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('save', 'Save'))

class ChemicalsubFactorCreateForm(forms.ModelForm):

    chemical = forms.ModelChoiceField(
                    queryset=Chemical.objects.all(),
                    required=False,
                    widget=autocomplete.ModelSelect2(url='/ontologies/chemical-autocomplete')
                    )

    class Meta:
        model = ChemicalsubFactor
        exclude = ("created_at", "created_by", "updated_at", "factor", )

    def __init__(self, *args, **kwargs):
        super(ChemicalsubFactorCreateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('save', 'Save'))

    def is_valid(self):
        valid = super(ChemicalsubFactorCreateForm, self).is_valid()

        if not valid:
            return valid

        if not self.cleaned_data['chemical'] and not self.cleaned_data['chemical_slug']:
            self.add_error("chemical", ValidationError(_('Please select either a chemical or a chemical slug'), code='invalid'))
            return False

        return True





class ChemicalsubFactorEditForm(ChemicalsubFactorCreateForm):

    def __init__(self, *args, **kwargs):
        super(ChemicalsubFactorCreateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('save', 'Save'))

toxsign/groups/forms.py
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout
from crispy_forms.bootstrap import FormActions

from django.contrib.auth.models import Group
from toxsign.users.models import Notification

class GroupCreateForm(forms.ModelForm):

    class Meta:
        model = Group
        fields = ["name"]

    def __init__(self, *args, **kwargs):
        super(GroupCreateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('save', 'Save'))

class GroupInvitationForm(forms.ModelForm):

    class Meta:
        model = Notification
        fields = ["user"]

    def __init__(self, *args, **kwargs):
        users = kwargs.pop('users', None)
        super(GroupInvitationForm, self).__init__( *args, **kwargs)
        if users:
            self.fields['user'].queryset = users
        else:
            self.fields['user'].widget.attrs['disabled'] = True
            self.fields['user'].label = "All users are already invited or members of the group."

toxsign/jobs/forms.py
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator

class GenerateRandomUserForm(forms.Form):
    total = forms.IntegerField(
        validators=[
            MinValueValidator(50),
            MaxValueValidator(500)
        ]
    )

toxsign/projects/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout
from crispy_forms.bootstrap import FormActions

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from toxsign.projects.models import Project

class ProjectCreateForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = ["name", "read_groups", "edit_groups", "description", "project_type", "superproject"]
        labels = {
            "read_groups": "Groups with viewing permissions",
            "edit_groups": "Groups with editing permissions",
            "superproject": "Link this project to a superproject you own"
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        self.project = kwargs.pop('project', None)
        self.superprojects =  kwargs.pop('superprojects', None)

        super(ProjectCreateForm, self).__init__(*args, **kwargs)
        self.fields['read_groups'].help_text = "Groups with viewing permission on project and subentities. Will be ignored if the visibility is set to public. Use 'ctrl' to select multiple/unselect."
        self.fields['edit_groups'].help_text = "Groups with editing permission on project and subentities. Use 'ctrl' to select multiple/unselect."

        # TODO : Give link to group creation interface?
        groups = self.user.groups.all()
        self.fields['read_groups'].queryset = groups
        self.fields['edit_groups'].queryset = groups

        if self.project:
            self.fields['name'].initial = self.project.name
            self.fields['description'].initial = self.project.description

            if all([group in groups for group in self.project.read_groups.all()]):
                self.fields['read_groups'].initial = self.project.read_groups.all()

            if all([group in groups for group in self.project.edit_groups.all()]):
                self.fields['edit_groups'].initial = self.project.edit_groups.all()

        if self.superprojects:
            self.fields['superproject'].queryset = self.superprojects
        else:
            self.fields['superproject'].widget.attrs['disabled'] = True

        self.helper = FormHelper(self)
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('save', 'Save'))


    def is_valid(self):
        valid = super(ProjectCreateForm, self).is_valid()
        if not valid:
            return valid

        for edit_group in self.cleaned_data['edit_groups']:
            if edit_group not in self.cleaned_data['read_groups']:
                self.add_error("edit_groups", ValidationError(_('Projects with editing rights must also have reading rights'), code='invalid'))
                return False
        return True

class ProjectEditForm(ProjectCreateForm):

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        self.superprojects =  kwargs.pop('superprojects', None)

        super(ProjectCreateForm, self).__init__(*args, **kwargs)
        self.fields['read_groups'].help_text = "Groups with viewing permission on project and subentities. Will be ignored if the visibility is set to public. Use 'ctrl' to select multiple/unselect."
        self.fields['edit_groups'].help_text = "Groups with editing permission on project and subentities. Use 'ctrl' to select multiple/unselect."

        # TODO : Give link to group creation interface?
        groups = self.user.groups.all()
        self.fields['read_groups'].queryset = groups
        self.fields['edit_groups'].queryset = groups

        if self.superprojects:
            self.fields['superproject'].queryset = self.superprojects
        else:
            self.fields['superproject'].widget.attrs['disabled'] = True

        self.helper = FormHelper(self)
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('save', 'Save'))

toxsign/templates/superprojects/details.html
{% extends "base.html" %}
{% load static i18n %}
{% load custom %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-3 ">
                <div class="list-group ">
                    <a href="#superproject" data-toggle="tab" class="list-group-item list-group-item-action {{is_active.superprojects}}">Superproject</a>
                    <a href="#projects" data-toggle="tab" class="list-group-item list-group-item-action {% if not projects %} disabled {% endif %}} {{is_active.projects}}">Related projects ({{ projects.paginator.count}})</a>
                </div>
            </div>
            <div class="col-md-9">
                <div class="tab-content card">
                    <div class="tab-pane text-style card-body {{is_active.superprojects}}" id="superproject">
                        <h2 style="text-align:center">{{ superproject.tsx_id }} - {{ superproject.name }}</h2>
                        <p><b>Description : </b>{% if superproject.created_by.is_superuser %} {{ superproject.description | safe }} {% else %} {{ superproject.description}} {% endif %}</p>
                        <p><b>Created : </b>{{ superproject.created_at }}</p>
                        <p><b>Owner : </b>{% show_username superproject %}</p>
                        {% if user.is_authenticated and superproject.contact_mail %}
                        <p><b>Contact : </b><a href="mailto:{{superproject.contact_mail}}">{{superproject.contact_mail}}</a></p>
                       {% endif %}
                    </div>
                    <div class="tab-pane text-style card-body {{is_active.projects}}" id="projects">
                        {% for project in projects %}
                            {% if project.visible %}
                            <h5><a href="{% url 'projects:detail' project.tsx_id %}">{{ project.tsx_id }}</a> - {{project.name}}</h5>
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <td>
                                            {% if project.status == "PUBLIC" %}<span class="badge badge-pill badge-success">Public</span>{% endif %}
                                            {% if project.status == "PENDING" %}<span class="badge badge-pill badge-secondary">Pending</span>{% endif %}
                                            {% if project.status == "PRIVATE" %}<span class="badge badge-pill badge-dark">Private</span>{% endif %}
                                            {% if project.project_type == "INTERVENTIONAL" %} <span class="badge badge-primary">Interventional</span>{% endif %}
                                            {% if project.project_type == "OBSERVATIONAL" %} <span class="badge badge-success">Observational</span>{% endif %}
                                        <td>
                                        <td>
                                        {% if project.description %}
                                            {{ project.description|safe|truncatewords:"30"|linebreaks }}
                                            <a style="color:blue;" href="{% url 'projects:detail' project.tsx_id %}">[more]</a>
                                        {% else %}
                                            No description provided
                                        {% endif %}
                                        </td>
                                        <td>
                                            {% show_username project %}
                                        </td>
                                        <td>
                                            {{ project.created_at }}
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            <hr>
                            {% else %}
                            <h5 style='text-align:center;' >{{ project.tsx_id }} - {{ project.name }}</h3>
                            <p style='text-align:center;'> Access to this project is restricted </p>
                            <hr>
                            {% endif %}
                            {% if superproject.created_by.username == user.username %}
                                <div style="float:right">
                                    <button data-url="{% url 'superprojects:superproject_unlink' superproject.tsx_id project.tsx_id %}" class="btn btn-danger js-remove">
                                        <i class="fas fa-unlink"></i> Unlink 
                                    </button>
                                </div>
                            {% endif %}
                        {% endfor %}
                        {% if projects %}
                        {% with table=projects type="projects" %}
                        {% include "pages/paginate.html" %}
                        {% endwith %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <br>
    </div>
    <div class="modal fade" id="modal-group">
        <div class="modal-dialog">
            <div class="modal-content"></div>
        </div>
    </div>

{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script>var token = '{{ csrf_token }}';</script>
    <script src="{% static 'js/superproject.js' %}"></script>
{% endblock %}

toxsign/templates/superprojects/partial_superproject_create.html
{% load crispy_forms_tags %}

<form method="post" action="{% url 'superprojects:superproject_create' %}" class="js-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Create a new superproject</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <p class="lead">Fill out your superproject name and a description</p>
        {{ form|crispy }}
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-default">Create</button>
    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
  </div>
</form>

toxsign/templates/superprojects/partial_superproject_edit.html
{% load crispy_forms_tags %}

<form method="post" action="{% url 'superprojects:superproject_edit' form.instance.tsx_id %}" class="js-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Create a new superproject</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <p class="lead">Fill out your superproject name and a description</p>
        {{ form|crispy }}
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-danger">Create</button>
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  </div>
</form>

toxsign/templates/superprojects/partial_superproject_project_remove.html
<form method="post" action="{% url 'superprojects:superproject_unlink' superproject.tsx_id project.tsx_id %}" class="js-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Unlink project</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to unlink the project {{project.name}} from the superproject?</p>
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-danger">Unlink project</button>
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  </div>
</form>

toxsign/templates/superprojects/superproject_edit.html
{% extends "base.html" %}
{% load static i18n %}
{% load account socialaccount %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container" style="margin-bottom:70px;">
        <h2> Editing {{ edit.tsx_id }} - {{ edit.name }}</h2>
        {% crispy form %}
    </div>
{% endblock %}