config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from . import views

urlpatterns = [
    path("", views.HomeView, name="home"),
    # Uncomment for maintenance
    #path("", views.MaintenanceView, name="maintenance"),
    path("search/", views.autocompleteModel, name="search"),
    path("advanced_search", views.advanced_search, name="advanced_search"),
    path("advanced_search_api", views.advanced_search_form, name="advanced_search_api"),
    path("index/", views.index, name="index"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path(
        "tutorial/", TemplateView.as_view(template_name="pages/tutorial.html"), name="tutorial"
    ),
    path(
        "statistics/", TemplateView.as_view(template_name="pages/statistics.html"), name="statistics"
    ),
    path("download/signature/<str:sigid>", views.download_signature, name="download_sig"),
    path("download/job/<int:jobid>", views.download_job_result, name="download_job"),
    path(
        "help/", TemplateView.as_view(template_name="pages/help.html"), name="help"
    ),
    path(
        "graphs/", views.graph_data, name="graph"
    ),
    path("unauthorized", views.render_403, name="unauthorized"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("groups/", include("toxsign.groups.urls", namespace="groups")),
    path("users/", include("toxsign.users.urls", namespace="users")),
    path("superprojects/", include("toxsign.superprojects.urls", namespace="superprojects")),
    path("projects/", include("toxsign.projects.urls", namespace="projects")),
    path("assays/", include("toxsign.assays.urls", namespace="assays")),
    path("signatures/", include("toxsign.signatures.urls", namespace="signatures")),
    path("tools/", include("toxsign.tools.urls", namespace="tools")),
    path("jobs/", include("toxsign.jobs.urls", namespace="jobs")),
    path("genes", include("toxsign.genes.urls", namespace="genes")),
    path("clusters/", include("toxsign.clusters.urls", namespace="clusters")),
    path("accounts/", include("allauth.urls")),
    path("ontologies/", include("toxsign.ontologies.urls", namespace="ontologies")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

toxsign/assays/urls.py
from django.urls import path
from toxsign.assays import views

app_name = "assays"
urlpatterns = [
    path('create/assay/<str:prjid>', views.CreateAssayView.as_view(), name='assay_create'),
    path('create/factor/<str:prjid>', views.CreateFactorView.as_view(), name='factor_create'),
    path('create/subfactor/<str:facid>/chemical', views.CreateChemicalsubFactorView.as_view(), name='chemical_subfactor_create'),
    path('factor/<str:facid>/', views.DetailFactorView, name='factor_detail'),
    path('factor/<str:facid>/subfactors', views.get_subfactors, name='factor_subfactor_detail'),
    path('assay/<str:assid>/', views.DetailAssayView, name='assay_detail'),
    path('edit/assay/<str:assid>/', views.EditAssayView.as_view(), name='assay_edit'),
    path('edit/factor/<str:facid>/', views.EditFactorView.as_view(), name='factor_edit'),
    path('edit/subfactor/chemical/<int:id>', views.EditChemicalsubFactorView.as_view(), name='chemical_subfactor_edit'),
    path('delete/subfactor/<str:type>/<int:id>', views.delete_subfactor, name='subfactor_delete'),
]

toxsign/genes/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'genes'
# Define urls here
urlpatterns = [
    re_path(r'^gene-autocomplete/$', GeneAutocomplete.as_view(), name='gene-autocomplete'),
    path('gene/<int:gene_id>', get_gene, name="get_gene")
]

toxsign/jobs/urls.py
from django.urls import path
from toxsign.jobs import views


app_name = 'jobs'
# Define urls here
urlpatterns = [
    # ex: /jobs/
    path('running_jobs/', views.running_jobs_view, name='running_jobs'),
    path('partial_running_jobs/', views.partial_running_jobs_view, name='partial_running_jobs'),
    path('delete_job/<int:pk>', views.Delete_job, name='delete_job'),
    # ex: /jobs/5/
    # the 'name' value as called by the {% url %} template tag
    path('<int:pk>/result', views.DetailView, name='results'),
    path('<int:pk>/result/<str:file_name>', views.DownloadView, name='results_download'),
]

toxsign/signatures/urls.py
from django.urls import path, re_path
from toxsign.signatures import views

app_name = "signatures"
urlpatterns = [
    path('create/<str:prjid>', views.CreateSignatureView.as_view(), name='signature_create'),
    path('edit/<str:sigid>', views.EditSignatureView.as_view(), name='signature_edit'),
    re_path(r'^signature-autocomplete/$', views.SignatureToolAutocomplete.as_view(), name='signature-autocomplete'),
    path('<str:sigid>/', views.DetailView, name='detail'),
]

toxsign/tools/urls.py
from django.urls import path
from toxsign.tools import views

app_name = 'tools'
# Define urls here
urlpatterns = [
    # ex: /tools/
    path('', views.IndexView.as_view(), name='index'),
    path('dist/results/<int:job_id>', views.distance_analysis_results, name='run_dist_results'),
    path('dist/results/<int:job_id>/table', views.distance_analysis_table, name='run_dist_table'),
    path('enrich/results/<int:job_id>', views.functional_analysis_results, name='run_enrich_results'),
    path('predict/results/<int:job_id>', views.prediction_tool_results, name='run_predict_results'),
    path('cluster_dist/results/<int:job_id>', views.cluster_dist_results, name='run_cluster_dist_results'),
    path('enrich/results/<int:job_id>/table', views.functional_analysis_full_table, name='run_enrich_table_full'),
    path('enrich/results/<int:job_id>/table/<str:type>', views.functional_analysis_partial_table, name='run_enrich_table_partial'),
    path('dist/', views.distance_analysis_tool, name='run_dist'),
    path('enrich/', views.functional_analysis_tool, name='run_enrich'),
    path('cluster_dist/', views.cluster_dist_tool, name='run_cluster_dist'),
    path('predict/', views.prediction_tool, name='run_predict'),
]

toxsign/users/urls.py
from django.urls import path

from toxsign.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
    dismiss_notification,
    accept_group_invitation
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
    path("notification/dismiss/<int:notification_id>", view=dismiss_notification, name="dismiss_notification"),
    path("notification/accept/<int:notification_id>", view=accept_group_invitation, name="accept_group_invitation"),
]

toxsign/assays/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import  User, Group
from django.conf import settings
from django.dispatch import receiver

import shutil
import os

from toxsign.projects.models import Project
from toxsign.ontologies.models import Biological, Cell, CellLine, Chemical, Disease, Experiment, Species, Tissue



class Assay(models.Model):
    DEVELOPPMENTAL_STAGE = (
        ("FETAL", 'Fetal'),
        ("EMBRYONIC", "Embryonic"),
        ("LARVA", "Larva"),
        ("NEONATAL", "Neo-natal"),
        ("JUVENILE", "Juvenile"),
        ("PREPUBERTAL", "Prepubertal"),
        ("ADULTHOOD", "Adulthood"),
        ("ELDERLY", "Elderly"),
        ("NA", "Na"),
        ("OTHER", "Other"),
    )
    GENERATION = (
        ("NA", "Na"),
        ('F0', 'F0'),
        ('F1', 'F1'),
        ('F2', 'F2'),
        ('F3', 'F3'),
        ('F4', 'F4'),
        ('F5', 'F5'),
    )
    SEX_TYPE = (
        ('MALE', 'Male'),
        ('FEMALE', 'Female'),
        ('BOTH', 'Both'),
        ("NA", "Na"),
        ("OTHER", "Other"),
    )
    EXPERIMENTAL_TYPE = (
        ('EXVIVO', 'Ex-vivo'),
        ('INVITRO', 'In-vitro'),
        ('INVIVO', 'In-vivo'),
        ("NA", "Na"),
        ("OTHER", "Other"),
    )

    name = models.CharField(max_length=500)
    tsx_id = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.CASCADE, related_name='%(app_label)s_%(class)s_created_by')
    updated_at = models.DateTimeField(auto_now=True, null=True, verbose_name=("user"))
    description = models.TextField("Description", blank=True)
    experimental_design = models.TextField("Experimental design", blank=True)
    additional_info = models.TextField("Additional information", blank=True)
    dev_stage = models.CharField(max_length=50, choices=DEVELOPPMENTAL_STAGE, default="NA")
    generation = models.CharField(max_length=10, choices=GENERATION, default="F0")
    sex_type = models.CharField(max_length=10, choices=SEX_TYPE, default="MALE")
    exp_type = models.CharField(max_length=10, choices=EXPERIMENTAL_TYPE, default="NA")
    project = models.ForeignKey(Project, blank=True, null=True, on_delete=models.CASCADE, related_name='assay_of')
    organism = models.ForeignKey(Species, blank=True, null=True, on_delete=models.CASCADE, related_name='assay_used_in')
    tissue = models.ForeignKey(Tissue, blank=True, null=True, on_delete=models.CASCADE, related_name='assay_used_in')
    cell = models.ForeignKey(Cell, blank=True, null=True, on_delete=models.CASCADE, related_name='assay_used_in')
    cell_line = models.ForeignKey(CellLine, blank=True, null=True, on_delete=models.CASCADE, related_name='assay_used_in')
    cell_line_slug = models.CharField(max_length=200, blank=True, null=True)
    results = models.TextField("Results", blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('assays:assay_detail', kwargs={"assid": self.tsx_id})

    # Override save method to auto increment tsx_id
    def save(self, *args, **kwargs):
        super(Assay, self).save(*args, **kwargs)
        self.tsx_id = "TSA" + str(self.id)
        super(Assay, self).save()

class Factor(models.Model):

    name = models.CharField(max_length=500)
    tsx_id = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.CASCADE, related_name='%(app_label)s_%(class)s_created_by')
    updated_at = models.DateTimeField(auto_now=True, null=True, verbose_name=("user"))
    assay = models.ForeignKey(Assay, blank=True, null=True, on_delete=models.CASCADE, related_name='factor_of')

    def __str__(self):
        return self.name

    # Redirect to assay page
    def get_absolute_url(self):
        return reverse('assays:factor_detail', kwargs={"facid": self.tsx_id})

    # Override save method to auto increment tsx_id
    def save(self, *args, **kwargs):
        super(Factor, self).save(*args, **kwargs)
        self.tsx_id = "TSF" + str(self.id)
        super(Factor, self).save()

class ChemicalsubFactor(models.Model):

    DOSE_UNIT = (
        ('NA', 'NA'),
        ('IC','IC'),
        ('EC','EC'),
        ('M','M'),
        ('mM','mM'),
        ('µM','µM'),
        ('nM','nM'),
        ('pM','pM'),
        ('fM','fM'),
        ('g/mL','g/mL'),
        ('mg/mL','mg/mL'),
        ('µg/mL','µg/mL'),
        ('ng/mL','ng/mL'),
        ('mg/kg','mg/kg'),
        ('µg/kg','µg/kg'),
        ('ng/kg','ng/kg'),
        ('ng/g lipid','ng/g lipid'),
        ('ng/g creatinine','ng/g creatinine'),
    )

    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.CASCADE, related_name='%(app_label)s_%(class)s_created_by')
    updated_at = models.DateTimeField(auto_now=True, null=True, verbose_name=("user"))
    factor = models.ForeignKey(Factor, on_delete=models.CASCADE, related_name='chemical_subfactor_of')
    chemical = models.ForeignKey(Chemical, blank=True, null=True, on_delete=models.CASCADE, related_name='chemical_subfactor_used_in')
    chemical_slug = models.CharField(max_length=500, blank=True)
    pubchemid = models.CharField(max_length=500, blank=True)
    CAS = models.CharField(max_length=500, blank=True)
    chemical_slug = models.CharField(max_length=500, blank=True)
    route = models.CharField(max_length=200, blank=True)
    vehicule = models.CharField(max_length=200, blank=True)
    dose_value = models.FloatField(null=True, blank=True, default=None)
    dose_unit = models.CharField(max_length=50, choices=DOSE_UNIT, default="M")
    exposure_time = models.FloatField(null=True, blank=True, default=None)
    exposure_frequencie = models.CharField(max_length=200, blank=True)
    additional_info = models.TextField("Additional information")

    # Redirect to factor page
    def get_absolute_url(self):
        return reverse('assays:factor_detail', kwargs={"facid": self.factor.tsx_id})

@receiver(models.signals.pre_delete, sender=Assay)
def auto_delete_assay_on_delete(sender, instance, **kwargs):
    # Delete the folder
    if not instance.project:
        return

    local_path = "{}/{}/".format(instance.project.tsx_id, instance.tsx_id)
    unix_path = settings.MEDIA_ROOT + "/files/" + local_path
    if(os.path.exists(unix_path)):
        shutil.rmtree(unix_path)

@receiver(models.signals.pre_delete, sender=Factor)
def auto_delete_factor_on_delete(sender, instance, **kwargs):
    # Delete the folder
    if not instance.assay or not instance.assay.project:
        return

    local_path = "{}/{}/{}/".format(instance.assay.project.tsx_id, instance.assay.tsx_id, instance.tsx_id)
    unix_path = settings.MEDIA_ROOT + "/files/" + local_path
    if(os.path.exists(unix_path)):
        shutil.rmtree(unix_path)

toxsign/groups/forms.py
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout
from crispy_forms.bootstrap import FormActions

from django.contrib.auth.models import Group
from toxsign.users.models import Notification

class GroupCreateForm(forms.ModelForm):

    class Meta:
        model = Group
        fields = ["name"]

    def __init__(self, *args, **kwargs):
        super(GroupCreateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('save', 'Save'))

class GroupInvitationForm(forms.ModelForm):

    class Meta:
        model = Notification
        fields = ["user"]

    def __init__(self, *args, **kwargs):
        users = kwargs.pop('users', None)
        super(GroupInvitationForm, self).__init__( *args, **kwargs)
        if users:
            self.fields['user'].queryset = users
        else:
            self.fields['user'].widget.attrs['disabled'] = True
            self.fields['user'].label = "All users are already invited or members of the group."

toxsign/jobs/forms.py
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator

class GenerateRandomUserForm(forms.Form):
    total = forms.IntegerField(
        validators=[
            MinValueValidator(50),
            MaxValueValidator(500)
        ]
    )

toxsign/superprojects/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout
from crispy_forms.bootstrap import FormActions

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from toxsign.superprojects.models import Superproject

class SuperprojectCreateForm(forms.ModelForm):

    class Meta:
        model = Superproject
        help_texts = {
            'contact_mail': 'Mail contact for projects included in this superproject. Will only be visible to logged users.',
            'description': 'A general description of this superproject'
        }
        fields = ["name", "contact_mail", "description"]

    def __init__(self, *args, **kwargs):
        super(SuperprojectCreateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('save', 'Save'))

class SuperprojectEditForm(SuperprojectCreateForm):
    pass

toxsign/templates/assays/assay_details.html
{% extends "base.html" %}
{% load static i18n %}
{% load custom %}

{% block content %}
<script src="https://d3js.org/d3.v5.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3-tip/0.9.1/d3-tip.min.js"></script>
<link href="{% static 'css/graph.css' %}" rel="stylesheet">
<script src="{% static 'js/graph.js' %}"></script>
<script src="{% static 'js/context-menu.js' %}"></script>
    <div class="container">
      <div class="tab-content card" style="text-align:center;">
        <div class="tab-pane active text-style card-body">
          <div id='graph'></div>
          <script>
            d3.json("{% url 'graph' %}?q={{project.tsx_id}}").then( function(json){
              drawGraph(json.data, json.max_parallel, json.max_depth, "{{assay.tsx_id}}");
            });
          </script>
        </div>
      </div>
      <br>
      <div class="row">
          <div class="col-md-12">
                <h2>{{ assay.tsx_id }} - {{ assay.name }} 
                
                {% if project.status == "PUBLIC" %}<span class="badge badge-pill badge-success">Public</span>{% endif %}
                {% if project.status == "PENDING" %}<span class="badge badge-pill badge-secondary">Pending</span>{% endif %}
                {% if project.status == "PRIVATE" %}<span class="badge badge-pill badge-dark">Private</span>{% endif %}
                {% if project.project_type == "INTERVENTIONAL" %} <span class="badge badge-primary">Interventional</span>{% endif %}
                {% if project.project_type == "OBSERVATIONAL" %} <span class="badge badge-success">Observational</span>{% endif %}
                
                </h2>
                <hr>
          </div>
      </div>
      <div class="row my-5">
          <div class="col-md-6 mb-5">
            <h2>Summary</h2>
            <table class="table">
              <tbody>
                <tr>
                  <th scope="row">Organism</th>
                  <td>
                    {% if assay.organism.name == "Homo sapiens" %} <img src="{% static 'images/species/Homo_sapiens.png' %}" width="50px" height="50px" data-toggle="tooltip" data-placement="top" title="{{assay.organism.name}}">{% endif %}
                    {% if assay.organism.name == "Canis familiaris" %} <img src="{% static 'images/species/Canis_familiaris.png' %}" width="50px" height="50px" data-toggle="tooltip" data-placement="top" title="{{assay.organism.name}}">{% endif %}
                    {% if assay.organism.name == "Danio rerio" %} <img src="{% static 'images/species/Danio_rerio.png' %}" width="50px" height="50px" data-toggle="tooltip" data-placement="top" title="{{assay.organism.name}}">{% endif %}
                    {% if assay.organism.name == "Drosophila melanogaster" %} <img src="{% static 'images/species/Drosophila_melanogaster.png' %}" width="50px" height="50px" data-toggle="tooltip" data-placement="top" title="{{assay.organism.name}}">{% endif %}
                    {% if assay.organism.name == "Macaca mulatta" %} <img src="{% static 'images/species/Macaca_mulatta.png' %}" width="50px" height="50px" data-toggle="tooltip" data-placement="top" title="{{assay.organism.name}}">{% endif %}
                    {% if assay.organism.name == "Mus musculus" %} <img src="{% static 'images/species/Mus_musculus.png' %}" width="50px" height="50px" data-toggle="tooltip" data-placement="top" title="{{assay.organism.name}}">{% endif %}
                    {% if assay.organism.name == "Rattus norvegicus" %} <img src="{% static 'images/species/Rattus_norvegicus.png' %}" width="50px" height="50px" data-toggle="tooltip" data-placement="top" title="{{assay.organism.name}}">{% endif %}
                    {% if assay.organism.name == "Sus scrofa" %} <img src="{% static 'images/species/Sus_scrofa.png' %}" width="50px" height="50px" data-toggle="tooltip" data-placement="top" title="{{assay.organism.name}}">{% endif %}
                  </td>
                  <td>{{ assay.organism.name }}</td>
                </tr>
                {% if assay.tissue %}
                  <tr>
                    <th scope="row">Tissue</th>
                    <td>
                      {% if assay.tissue.name == "Liver" or assay.tissue.name == "liver" %} <img src="{% static 'images/organs/png/028-liver.png' %}" width="50px" height="50px" data-toggle="tooltip" data-placement="top" title="{{assay.tissue.name}}">{% endif %}
                      {% if assay.tissue.name == "Kidney" or assay.tissue.name == "kidney" %} <img src="{% static 'images/organs/png/008-kidneys-1.png' %}" width="50px" height="50px" data-toggle="tooltip" data-placement="top" title="{{assay.tissue.name}}">{% endif %}
                      {% if assay.tissue.name == "Brain" or assay.tissue.name == "brain" %} <img src="{% static 'images/organs/png/002-brain.png' %}" width="50px" height="50px" data-toggle="tooltip" data-placement="top" title="{{assay.tissue.name}}">{% endif %}
                      {% if assay.tissue.name == "Lungs" or assay.tissue.name == "lungs" %} <img src="{% static 'images/organs/png/003-lungs.png' %}" width="50px" height="50px" data-toggle="tooltip" data-placement="top" title="{{assay.tissue.name}}">{% endif %}
                      {% if assay.tissue.name == "Bladder" or assay.tissue.name == "bladder" %} <img src="{% static 'images/organs/png/006-bladder.png' %}" width="50px" height="50px" data-toggle="tooltip" data-placement="top" title="{{assay.tissue.name}}">{% endif %}
                      {% if assay.tissue.name == "Testis" or assay.tissue.name == "testis" %} <img src="{% static 'images/organs/png/022-testicle.png' %}" width="50px" height="50px" data-toggle="tooltip" data-placement="top" title="{{assay.tissue.name}}">{% endif %}
                      {% if assay.tissue.name == "Heart" or assay.tissue.name == "heart" %} <img src="{% static 'images/organs/png/023-heart.png' %}" width="50px" height="50px" data-toggle="tooltip" data-placement="top" title="{{assay.tissue.name}}">{% endif %}
                      {% if assay.tissue.name == "Ovary" or assay.tissue.name == "ovary" %} <img src="{% static 'images/organs/png/024-uterus.png' %}" width="50px" height="50px" data-toggle="tooltip" data-placement="top" title="{{assay.tissue.name}}">{% endif %}
                      {% if assay.tissue.name == "Stomach" or assay.tissue.name == "stomach" %} <img src="{% static 'images/organs/png/029-stomach.png' %}" width="50px" height="50px" data-toggle="tooltip" data-placement="top" title="{{assay.tissue.name}}">{% endif %}
                      {% if assay.tissue.name == "Intestine" or assay.tissue.name == "intestine" %} <img src="{% static 'images/organs/png/027-intestine.png' %}" width="50px" height="50px" data-toggle="tooltip" data-placement="top" title="{{assay.tissue.name}}">{% endif %}
                    </td>
                    <td>{{assay.tissue.name}}</td>
                  </tr>
                {% endif %}
                {% if assay.cell %}
                  <tr><th scope="row">Cell</th><td><img src="{% static 'images/organs/png/014-cells.png' %}" width="50px" height="50px"></td><td>{{assay.cell}}</td></tr>
                {% endif %}
                {% if assay.cell_line %}
                  <tr><th scope="row">Cell line</th><td><img src="{% static 'images/organs/png/014-cells.png' %}" width="50px" height="50px"></td><td>{{assay.cell_line}}</td></tr>
                {% endif %}
              </tbody>
            </table>
          </div>
          <div class="col-md-6 mb-5">
                <h2>Characteristics</h2>
                <table class="table">
                  <tbody>
                    {% if assay.exp_type %}<tr><th scope="row">Experimental type</th><td>{{ assay.get_exp_type_display }}</td></tr>{% endif %}
                    {% if assay.sex_type %}<tr><th scope="row">Sex</th><td>{{ assay.get_sex_type_display }}</td></tr>{% endif %}
                    {% if assay.generation %}<tr><th scope="row">Generation</th><td>{{ assay.get_generation_display }}</td></tr>{% endif %}
                    {% if assay.dev_stage %}<tr><th scope="row">Developmental stage</th><td>{{ assay.get_dev_stage_display }}</td></tr>{% endif %}
                  </tbody>
                </table>
          </div>
      </div>
      <div class="row my-5">
          <div class="col-md-6 mb-5">
                <h2>
                  Experimental design
                </h2>
                <hr>
                <p>{% if assay.experimental_design %} {{ assay.experimental_design }} {% else %} No experimental design provided {% endif %}</p>
          </div>
          <div class="col-md-6 mb-5">
                <h2>Additional information</h2>
                <hr>
                <p>{% if assay.additional_info %} {{ assay.additional_info }} {% else %} No additional information provided {% endif %}</p>
          </div>
      </div>

      {% if project.created_by == request.user%}
        <div class="row my-5">
            <div class="col-md-8 mb-5">
                  <h2>Authorization</h2>
                  <table class="table">
                    </thead>
                    <tbody>
                      <tr>
                        <th scope="row">Read group</th>
                        <td>
                          {% for read in project.read_groups.all %}
                            <span>{{ read }}</span>
                          {% endfor %}
                        </td>
                      </tr>
                      <tr>
                        <th scope="row">Edit group</th>
                        <td>
                          {% for edit in project.edit_groups.all %}
                            <span>{{ edit }}</span>
                          {% endfor %}
                        </td>
                      </tr>
                    </tbody>
                  </table>
            </div>
            <div class="col-md-4 mb-5">
                  <h2>Information</h2>
                  <table class="table">
                    </thead>
                    <tbody>
                      <tr>
                        <th scope="row">Owner</th>
                        <td>{% show_username assay %}</td>
                      </tr>
                      <tr>
                        <th scope="row">Creation date</th>
                        <td>{{ assay.created_at }}</td>
                      </tr>
                      <tr>
                        <th scope="row">Last update</th>
                        <td>{{ assay.updated_at }}</td>
                      </tr>
                    </tbody>
                  </table>
            </div>
        </div>
      {% endif %}

      
      

    </div>
    <div class="modal fade" id="modal-group">
        <div class="modal-dialog modal-lg">
            <div class="modal-content"></div>
        </div>
    </div>

{% endblock %}
{% block javascript %}
  {{block.super}}
  <script>
      $(function () {
        $('[data-toggle="tooltip"]').tooltip()
      })
    </script>
{% endblock %}