config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from . import views

urlpatterns = [
    path("", views.HomeView, name="home"),
    # Uncomment for maintenance
    #path("", views.MaintenanceView, name="maintenance"),
    path("search/", views.autocompleteModel, name="search"),
    path("advanced_search", views.advanced_search, name="advanced_search"),
    path("advanced_search_api", views.advanced_search_form, name="advanced_search_api"),
    path("index/", views.index, name="index"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path(
        "tutorial/", TemplateView.as_view(template_name="pages/tutorial.html"), name="tutorial"
    ),
    path(
        "statistics/", TemplateView.as_view(template_name="pages/statistics.html"), name="statistics"
    ),
    path("download/signature/<str:sigid>", views.download_signature, name="download_sig"),
    path("download/job/<int:jobid>", views.download_job_result, name="download_job"),
    path(
        "help/", TemplateView.as_view(template_name="pages/help.html"), name="help"
    ),
    path(
        "graphs/", views.graph_data, name="graph"
    ),
    path("unauthorized", views.render_403, name="unauthorized"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("groups/", include("toxsign.groups.urls", namespace="groups")),
    path("users/", include("toxsign.users.urls", namespace="users")),
    path("superprojects/", include("toxsign.superprojects.urls", namespace="superprojects")),
    path("projects/", include("toxsign.projects.urls", namespace="projects")),
    path("assays/", include("toxsign.assays.urls", namespace="assays")),
    path("signatures/", include("toxsign.signatures.urls", namespace="signatures")),
    path("tools/", include("toxsign.tools.urls", namespace="tools")),
    path("jobs/", include("toxsign.jobs.urls", namespace="jobs")),
    path("genes", include("toxsign.genes.urls", namespace="genes")),
    path("clusters/", include("toxsign.clusters.urls", namespace="clusters")),
    path("accounts/", include("allauth.urls")),
    path("ontologies/", include("toxsign.ontologies.urls", namespace="ontologies")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

toxsign/genes/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'genes'
# Define urls here
urlpatterns = [
    re_path(r'^gene-autocomplete/$', GeneAutocomplete.as_view(), name='gene-autocomplete'),
    path('gene/<int:gene_id>', get_gene, name="get_gene")
]

toxsign/groups/urls.py
from django.urls import path
from toxsign.groups import views

app_name = "groups"
urlpatterns = [
    path('<int:grpid>/', views.DetailView, name='detail'),
    path('create/', views.create_group, name='create'),
    path('invite/<int:group_id>', views.send_invitation, name='invite_user'),
    path('<int:group_id>/remove/<int:user_to_remove_id>', views.remove_user_from_group, name='remove_user'),
    path('<int:group_id>/changeowner/<int:new_owner_id>', views.set_owner, name='change_owner'),
]

toxsign/jobs/urls.py
from django.urls import path
from toxsign.jobs import views


app_name = 'jobs'
# Define urls here
urlpatterns = [
    # ex: /jobs/
    path('running_jobs/', views.running_jobs_view, name='running_jobs'),
    path('partial_running_jobs/', views.partial_running_jobs_view, name='partial_running_jobs'),
    path('delete_job/<int:pk>', views.Delete_job, name='delete_job'),
    # ex: /jobs/5/
    # the 'name' value as called by the {% url %} template tag
    path('<int:pk>/result', views.DetailView, name='results'),
    path('<int:pk>/result/<str:file_name>', views.DownloadView, name='results_download'),
]

toxsign/projects/urls.py
from django.urls import path
from toxsign.projects import views

app_name = "projects"
urlpatterns = [
    path('create/', views.CreateProjectView.as_view(), name='project_create'),
    path('edit/<str:prjid>/', views.EditProjectView.as_view(), name='project_edit'),
    path('publicize/<str:prjid>/', views.publicize_project, name='project_publicize'),
    path('<str:prjid>/', views.DetailView, name='detail'),
]

toxsign/superprojects/urls.py
from django.urls import path
from toxsign.superprojects import views

app_name = "superprojects"
urlpatterns = [
    path('create/', views. create_superproject, name='superproject_create'),
    path('edit/<str:spjid>/', views.edit_superproject, name='superproject_edit'),
    path('unlink/<str:spjid>/<str:prjid>', views.unlink_project, name='superproject_unlink'),
    path('<str:spjid>/', views.DetailView, name='detail')
]

toxsign/tools/urls.py
from django.urls import path
from toxsign.tools import views

app_name = 'tools'
# Define urls here
urlpatterns = [
    # ex: /tools/
    path('', views.IndexView.as_view(), name='index'),
    path('dist/results/<int:job_id>', views.distance_analysis_results, name='run_dist_results'),
    path('dist/results/<int:job_id>/table', views.distance_analysis_table, name='run_dist_table'),
    path('enrich/results/<int:job_id>', views.functional_analysis_results, name='run_enrich_results'),
    path('predict/results/<int:job_id>', views.prediction_tool_results, name='run_predict_results'),
    path('cluster_dist/results/<int:job_id>', views.cluster_dist_results, name='run_cluster_dist_results'),
    path('enrich/results/<int:job_id>/table', views.functional_analysis_full_table, name='run_enrich_table_full'),
    path('enrich/results/<int:job_id>/table/<str:type>', views.functional_analysis_partial_table, name='run_enrich_table_partial'),
    path('dist/', views.distance_analysis_tool, name='run_dist'),
    path('enrich/', views.functional_analysis_tool, name='run_enrich'),
    path('cluster_dist/', views.cluster_dist_tool, name='run_cluster_dist'),
    path('predict/', views.prediction_tool, name='run_predict'),
]

toxsign/users/urls.py
from django.urls import path

from toxsign.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
    dismiss_notification,
    accept_group_invitation
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
    path("notification/dismiss/<int:notification_id>", view=dismiss_notification, name="dismiss_notification"),
    path("notification/accept/<int:notification_id>", view=accept_group_invitation, name="accept_group_invitation"),
]

toxsign/genes/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import  User, Group
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.apps import apps

class Gene(models.Model):

    gene_id =  models.CharField(max_length=50)
    tax_id =  models.CharField(max_length=50, blank=True)
    symbol =  models.CharField(max_length=50, blank=True)
    synonyms =  models.TextField(blank=True)
    description =  models.TextField(blank=True)
    homolog_id =  models.CharField(max_length=50, blank=True)
    ensembl_id =  models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.gene_id

class Pathway(models.Model):

    name = models.CharField(max_length=200)
    pathway_id = models.CharField(max_length=50)
    organism =  models.CharField(max_length=50)
    genes = models.ManyToManyField(Gene, related_name="pathways")

toxsign/assays/forms.py
from django import forms

from django.forms.models import inlineformset_factory

from dal import autocomplete
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout
from crispy_forms.bootstrap import FormActions
from toxsign.assays.models import Assay, Factor, ChemicalsubFactor
from toxsign.ontologies.models import Cell, CellLine, Chemical, Species, Tissue

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


class AssayCreateForm(forms.ModelForm):

    cell_line = forms.ModelChoiceField(
                    queryset=CellLine.objects.all(),
                    required=False,
                    widget=autocomplete.ModelSelect2(url='/ontologies/cellline-autocomplete')
                    )
    cell = forms.ModelChoiceField(
                queryset=Cell.objects.all(),
                required=False,
                widget=autocomplete.ModelSelect2(url='/ontologies/cell-autocomplete')
                )
    organism = forms.ModelChoiceField(
                    queryset=Species.objects.all(),
                    required=False,
                    widget=autocomplete.ModelSelect2(url='/ontologies/species-autocomplete')
                    )
    tissue = forms.ModelChoiceField(
                queryset=Tissue.objects.all(),
                required=False,
                widget=autocomplete.ModelSelect2(url='/ontologies/tissue-autocomplete')
                )

    class Meta:
        model = Assay
        exclude = ("tsx_id", "created_at", "created_by", "updated_at", "project")

    def __init__(self, *args, **kwargs):
        self.assay = kwargs.pop('assay', None)

        super(AssayCreateForm, self).__init__(*args, **kwargs)

        if self.assay:
            self.fields['name'].initial = self.assay.name
            self.fields['additional_info'].initial = self.assay.additional_info
            self.fields['experimental_design'].initial = self.assay.experimental_design
            self.fields['dev_stage'].initial = self.assay.dev_stage
            self.fields['generation'].initial = self.assay.generation
            self.fields['sex_type'].initial = self.assay.sex_type
            self.fields['exp_type'].initial = self.assay.exp_type
            self.fields['project'].initial = self.assay.project
            self.fields['organism'].initial = self.assay.organism
            self.fields['tissue'].initial = self.assay.tissue
            self.fields['cell'].initial = self.assay.cell
            self.fields['cell_line'].initial = self.assay.cell_line

        self.helper = FormHelper(self)
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('save', 'Save'))


class AssayEditForm(AssayCreateForm):

    def __init__(self, *args, **kwargs):
        super(AssayCreateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('save', 'Save'))


class FactorCreateForm(forms.ModelForm):

    class Meta:
        model = Factor
        exclude = ("tsx_id", "created_at", "created_by", "updated_at", )

    def __init__(self, *args, **kwargs):
        self.assays = kwargs.pop('assay')
        self.factor = kwargs.pop('factor', None)

        super(FactorCreateForm, self).__init__(*args, **kwargs)

        self.fields['assay'].queryset = self.assays
        if self.assays.count() == 1:
            self.fields['assay'].initial = self.assays.first()

        if self.factor:
            self.fields['name'].initial = self.factor.name
            self.fields['assay'].initial = self.factor.assay

        self.helper = FormHelper(self)
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('save', 'Save'))

class FactorEditForm(FactorCreateForm):

    def __init__(self, *args, **kwargs):
        self.assays = kwargs.pop('assay')
        super(FactorCreateForm, self).__init__(*args, **kwargs)
        self.fields['assay'].queryset = self.assays
        self.helper = FormHelper(self)
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('save', 'Save'))

class ChemicalsubFactorCreateForm(forms.ModelForm):

    chemical = forms.ModelChoiceField(
                    queryset=Chemical.objects.all(),
                    required=False,
                    widget=autocomplete.ModelSelect2(url='/ontologies/chemical-autocomplete')
                    )

    class Meta:
        model = ChemicalsubFactor
        exclude = ("created_at", "created_by", "updated_at", "factor", )

    def __init__(self, *args, **kwargs):
        super(ChemicalsubFactorCreateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('save', 'Save'))

    def is_valid(self):
        valid = super(ChemicalsubFactorCreateForm, self).is_valid()

        if not valid:
            return valid

        if not self.cleaned_data['chemical'] and not self.cleaned_data['chemical_slug']:
            self.add_error("chemical", ValidationError(_('Please select either a chemical or a chemical slug'), code='invalid'))
            return False

        return True





class ChemicalsubFactorEditForm(ChemicalsubFactorCreateForm):

    def __init__(self, *args, **kwargs):
        super(ChemicalsubFactorCreateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('save', 'Save'))

toxsign/groups/forms.py
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout
from crispy_forms.bootstrap import FormActions

from django.contrib.auth.models import Group
from toxsign.users.models import Notification

class GroupCreateForm(forms.ModelForm):

    class Meta:
        model = Group
        fields = ["name"]

    def __init__(self, *args, **kwargs):
        super(GroupCreateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('save', 'Save'))

class GroupInvitationForm(forms.ModelForm):

    class Meta:
        model = Notification
        fields = ["user"]

    def __init__(self, *args, **kwargs):
        users = kwargs.pop('users', None)
        super(GroupInvitationForm, self).__init__( *args, **kwargs)
        if users:
            self.fields['user'].queryset = users
        else:
            self.fields['user'].widget.attrs['disabled'] = True
            self.fields['user'].label = "All users are already invited or members of the group."

toxsign/jobs/forms.py
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator

class GenerateRandomUserForm(forms.Form):
    total = forms.IntegerField(
        validators=[
            MinValueValidator(50),
            MaxValueValidator(500)
        ]
    )

toxsign/superprojects/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout
from crispy_forms.bootstrap import FormActions

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from toxsign.superprojects.models import Superproject

class SuperprojectCreateForm(forms.ModelForm):

    class Meta:
        model = Superproject
        help_texts = {
            'contact_mail': 'Mail contact for projects included in this superproject. Will only be visible to logged users.',
            'description': 'A general description of this superproject'
        }
        fields = ["name", "contact_mail", "description"]

    def __init__(self, *args, **kwargs):
        super(SuperprojectCreateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('save', 'Save'))

class SuperprojectEditForm(SuperprojectCreateForm):
    pass

toxsign/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from toxsign.users.models import Notification, User

class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User
        fields = ['name', 'last_name', 'institut', 'email', 'username']
        labels = {
            "name": "Name",
            "last_name": "Last name",
            "institut": "Institute"
        }

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

toxsign/templates/users/partial_notif_dismiss.html
<form method="post" action="{% url 'users:dismiss_notification' notification.id %}" class="js-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Refuse group invitation</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to refuse this invitation to the group {{group.name}}? You will not be able to access data restricted to this group.</p>
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-danger">Dismiss invitation</button>
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  </div>
</form>

toxsign/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">
    <h2 class="m-y-2">Profile</h2>
    <div class="row m-y-2">
        <div class="col-lg-12 push-lg-12">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a href="" data-target="#profile" data-toggle="tab" class="nav-link {{in_use.user}}">Profile</a>
                </li>
                {% if object == request.user %}
                  <li class="nav-item">
                      <a href="" data-target="#notifications" data-toggle="tab" class="nav-link {{in_use.notification}}">Notifications ({{ notifications.paginator.count }})</a>
                  </li>
                  <li class="nav-item">
                      <a href="" data-target="#groups" data-toggle="tab" class="nav-link">My groups  ({{ groups.paginator.count }})</a>
                  </li>
                  <li class="nav-item">
                      <a href="" data-target="#superprojects" data-toggle="tab" class="nav-link {{in_use.superproject}}">My superprojects ({{ superprojects.paginator.count }})</a>
                  </li>
                  <li class="nav-item">
                      <a href="" data-target="#project" data-toggle="tab" class="nav-link {{in_use.project}}">My projects ({{ projects.paginator.count }})</a>
                  </li>
                {% endif %}
            </ul>
            <div class="tab-content p-b-3" style="margin-top:20px;">
                <div class="tab-pane {{in_use.user}}" id="profile">
                    <div class="row">
                      <div class="col-md-12">
                        <form>
                          <div class="form-group">
                            <label for="exampleInputUser">User name</label>
                            <input type="text" class="form-control" id="exampleInputUser" aria-describedby="UserHelp" placeholder="" value="{{ object.username }}" disabled>
                            <small id="UserHelp" class="form-text text-muted">Can't be modified</small>
                          </div>
                          <div class="form-group">
                            <label for="exampleInputmail">Email</label>
                            <input type="text" class="form-control" id="exampleInputmail" aria-describedby="MailHelp" placeholder="" value="{{ object.email }}" disabled>
                          </div>
                          <div class="form-group">
                            <label for="exampleInputFirst">First name</label>
                            <input type="text" class="form-control" id="exampleInputFirst" aria-describedby="FirstHelp" placeholder="Enter email" value="{{ object.name }}" disabled>
                          </div>
                          <div class="form-group">
                            <label for="exampleInputLast">Last name</label>
                            <input type="text" class="form-control" id="exampleInputLast" aria-describedby="LastHelp" placeholder="Click on modify to change your last name" value="{{ object.last_name }}" disabled>
                          </div>
                          <div class="form-group">
                            <label for="exampleInputCompagny">Institut</label>
                            <input type="text" class="form-control" id="exampleInputCompagny" placeholder="Click on modify to change your compagny" value="{{ object.institut }}" disabled>
                          </div>
                        </form>
                        {% if object == request.user %}
                        <!-- Action buttons -->
                        <div class="row">

                          <div class="col-sm-12">
                            <a class="btn btn-outline-info" href="{% url 'users:update' %}" role="button">Edit info</a>
                            <a class="btn btn-outline-info" href="{% url 'account_email' %}" role="button">E-Mail</a>
                            <!-- Your Stuff: Custom user template urls -->
                          </div>

                        </div>
                        <!-- End Action buttons -->
                        {% endif %}
                      </div>
                    </div>
                </div>
                {% if object == request.user %}
                <div class="tab-pane {{in_use.notification}}" id="notifications">
                <h2>My notifications</h2>
                <div class="table-responsive-xl">
                    <table class="table table-hover" id="notification_list">
                        <thead>
                            <tr style="text-align:center;">
                                <th scope="col">Sent by</th>
                                <th scope="col">Message</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                    <tbody>
                        {% for notification in notifications %}
                        <tr style="text-align:center;">
                            <td>{{notification.created_by}}</td>
                            <td>{{notification.message}}</td>
                            <td>
                                {% if notification.type == 'GROUP' %}
                                <button type="button" class="btn btn-success btn-sm js-notif-action" data-url="{% url 'users:accept_group_invitation' notification.id %}">
                                <span class="glyphicon glyphicon-trash"></span> Accept 
                                </button>
                                <button type="button" class="btn btn-danger btn-sm js-refuse-invitation" data-url="{% url 'users:dismiss_notification' notification.id %}">
                                <span class="glyphicon glyphicon-trash"></span> Dismiss 
                                </button>
                                {% else %}
                                <button type="button" class="btn btn-danger btn-sm js-notif-action" data-url="{% url 'users:dismiss_notification' notification.id %}">
                                <span class="glyphicon glyphicon-trash"></span> Dismiss 
                                </button>
                                {% endif %} 
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    </table>
                    {% if notifications %}
                    {% with table=notifications type="notifications" %}
                    {% include "pages/paginate.html" %}
                    {% endwith %}
                    {% endif %}
                </div>
                </div>
                <div class="tab-pane" id="groups">
                <h2>My groups <button data-url="{% url 'groups:create' %}" class="btn btn-outline-info js-create float-right"><i class="fas fa-external-link-alt"></i>New</button></h2>
                <div class="table-responsive-xl">
                    <table class="table table-hover">
                        <thead>
                            <tr style="text-align:center;">
                                <th scope="col">Name</th>
                                <th scope="col">Members</th>
                                <th scope="col">Group owner?</th>
                            </tr>
                        </thead>
                    <tbody>
                        {% for group in groups %}
                        <tr style="text-align:center;">
                            <td><a href="{% url 'groups:detail' group.id %}">{{group.name}}</a></td>
                            <td>{{group.members_number}}</td>
                            {% if group.ownership.owner == request.user %}
                            <td><i class="fas fa-check"></i></td>
                            {% else %}
                            <td>{{group.ownership.owner.username}}</td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </tbody>
                    </table>
                    {% if groups %}
                    {% with table=groups type="groups" %}
                    {% include "pages/paginate.html" %}
                    {% endwith %}
                    {% endif %}
                </div>
                </div>
                <div class="tab-pane {{in_use.superproject}}" id="superprojects">
                <h2>My superprojects <a role="button" data-url="{% url 'superprojects:superproject_create' %}" class="btn btn-outline-info js-create float-right"><i class="fas fa-external-link-alt"></i> New</a></h2>
                  <div class="table-responsive-xl">
                    <table class="table table-hover">
                      <thead>
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">Name</th>
                          <th scope="col">Creation date</th>
                          <th scope="col">Action</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for superproject in superprojects %}
                          <tr>
                            <th><a href="{% url 'superprojects:detail' superproject.tsx_id %}">{{ superproject.tsx_id }}</a></th>
                            <td>{{ superproject.name }}</td>
                            <td>{{ superproject.created_at }}</td>
                            <td>
                              <a role="button" data-url="{% url 'superprojects:superproject_edit' superproject.tsx_id %}" class="btn btn-outline-success js-create"><i class="far fa-edit"></i> Edit</a>
                              <a role="button" href="#" class="btn btn-outline-danger"><i class="far fa-trash-alt"></i> Delete</a>
                            </td>
                          </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                    {% if superprojects %}
                    {% with table=superprojects type="superprojects" %}
                    {% include "pages/paginate.html" %}
                    {% endwith %}
                    {% endif %}
                  </div>
                </div>
                <div class="tab-pane {{in_use.project}}" id="project">
                <h2>My projects <a role="button" href="{% url 'projects:project_create' %}" class="btn btn-outline-info float-right"><i class="fas fa-external-link-alt"></i> New</a></h2>
                  <div class="table-responsive-xl">
                    <table class="table table-hover">
                      <thead>
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">Name</th>
                          <th scope="col">Creation date</th>
                          <th scope="col">Status</th>
                          <th scope="col">Action</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for project in projects %}
                          <tr>
                            <th><a href="{% url 'projects:detail' project.tsx_id %}">{{ project.tsx_id }}</a></th>
                            <td>{{ project.name }}</td>
                            <td>{{ project.created_at }}</td>
                            <td>{{ project.status }}</td>
                            <td>
                              {% if project.permissions.edit %}
                              <a role="button" href="{% url 'projects:project_edit' project.tsx_id %}" class="btn btn-outline-success"><i class="far fa-edit"></i> Edit</a>
                              {% endif %}
                              {% if project.permissions.delete %}
                              <a role="button" href="#" class="btn btn-outline-danger"><i class="far fa-trash-alt"></i> Delete</a>
                              {% endif %}
                            </td>
                          </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                    {% if projects %}
                    {% with table=projects type="projects" %}
                    {% include "pages/paginate.html" %}
                    {% endwith %}
                    {% endif %}
                  </div>
                </div>
               </div>
               {% endif %}
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modal-group">
    <div class="modal-dialog">
        <div class="modal-content"></div>
    </div>
</div>
<hr>
</div>


{% endblock content %}

{% block javascript %}
    {{ block.super }}
    <script>var token = '{{ csrf_token }}';</script>
    <script src="{% static 'js/user.js' %}"></script>
{% endblock %}